### ISSUE TITLE
[0.8-beta.1] PGPKey isEqual: / hash not working correctly

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#71]
For example, let's say we look for key: `434F622F68D8C433` at address `0x60800003ad20`
```
(lldb) po self.allKeys
{(
    <PGPKey: 0x60800003a480>, publicKey: 62FC4AA884E326BF, secretKey: 62FC4AA884E326BF,
    <PGPKey: 0x6080000314e0>, publicKey: B79FB5CD6BBE1C56, secretKey: B79FB5CD6BBE1C56,
    <PGPKey: 0x60800003a140>, publicKey: 589512AB12907BB4, secretKey: 589512AB12907BB4,
    <PGPKey: 0x60800003ad20>, publicKey: 434F622F68D8C433, secretKey: 434F622F68D8C433,
    <PGPKey: 0x60800003b200>, publicKey: 5C2BDD37197EC6D7, secretKey: 5C2BDD37197EC6D7,
    <PGPKey: 0x60800003b9a0>, publicKey: 8324917E676A89B0, secretKey: 8324917E676A89B0,
    <PGPKey: 0x60800003a8e0>, publicKey: A516B4F8DE4E1BCC, secretKey: A516B4F8DE4E1BCC,
    <PGPKey: 0x6080000352e0>, publicKey: 55D92967FD8845DA, secretKey: 55D92967FD8845DA
)}

(lldb) po key
<PGPKey: 0x60800003ad20>, publicKey: 434F622F68D8C433, secretKey: 434F622F68D8C433

(lldb) po (BOOL)[self.allKeys containsObject:key]
NO
```

**Comment by dsanghan** [comment]
Seems like its an issue with NSSet's and not NSArray's:
```
(lldb) p (BOOL)[[self.allKeys allObjects] containsObject:key]
(BOOL) $102 = YES
(lldb) p (BOOL)[self.allKeys containsObject:key]
(BOOL) $103 = NO
```

**Comment by krzyzanowskim** [comment]
Thanks for catching up. Need to add tests for that.

**Comment by dsanghan** [comment]
Yeah, figured it out. You're using `super.hash` in `PGPKeyID`'s hash function as the base hash. That should just be 1 or 0.

**Comment by dsanghan** [comment]
Or rather just use `longKey.hash`

**Comment by dsanghan** [comment]
Also, isEqual is incorrect in PGPKey.m, it should be something like:

```
- (BOOL)isEqualToKey:(PGPKey *)other {
    if (self.secretKey && other.secretKey) {
        if (![self.secretKey isEqual:other.secretKey]) {
            return NO;
        }
    }
    if (self.publicKey && other.publicKey) {
        if (![self.publicKey isEqual:other.publicKey]) {
            return NO;
        }
    }
    return self.isSecret == other.isSecret && self.isPublic && other.isPublic;
}
```

because comparing two nil public keys / nil secret keys will return NO

**Comment by dsanghan** [comment]
In `equalToPartialKey:`
```
return self.type == other.type &&
            self.isEncrypted == other.isEncrypted &&
            [self.primaryKeyPacket isEqual:other.primaryKeyPacket] && // returns incorrect false
            [self.users isEqual:other.users] &&                                            // returns incorrect false
            [self.subKeys isEqual:other.subKeys] &&
            [self.directSignatures isEqual:other.directSignatures] &&
            [self.revocationSignature isEqual:other.revocationSignature] &&
            [self.keyID isEqual:other.keyID];
```

**Comment by krzyzanowskim** [comment]
true, I have to start using `PGPCompareObjects`, forgot to go along with that.

**Comment by dsanghan** [comment]
Yup. Here's rough commits for the fix:

https://github.com/dsanghan/ObjectivePGP/commit/d1be1c04438fbe5cb71da4e39b3732ba2a87b28d
https://github.com/dsanghan/ObjectivePGP/commit/f89b180b842f7c11b8aacdf204231684e30c4947

**Comment by krzyzanowskim** [comment]
fixed in v 0.8

**Comment by dsanghan** [comment]
Still not working correctly on iOS :(

```
(lldb) po self.allKeys
{(
    <PGPKey: 0x1c483ad80>, publicKey: B19BCCD6E4598D3D, secretKey: B19BCCD6E4598D3D,
    <PGPKey: 0x1c0a30020>, publicKey: 45F9449E3FB5CE03, secretKey: 45F9449E3FB5CE03,
    <PGPKey: 0x1c0434fc0>, publicKey: 94EE9BCC9A94FA24, secretKey: (null),
    <PGPKey: 0x1c483af80>, publicKey: BA917FC403ECE9B0, secretKey: BA917FC403ECE9B0,
    <PGPKey: 0x1c0a30400>, publicKey: 76D78F0500D026C4, secretKey: (null)
)}
(lldb) po key
<PGPKey: 0x1c483af80>, publicKey: BA917FC403ECE9B0, secretKey: BA917FC403ECE9B0
(lldb) p (BOOL)[self.allKeys.allObjects containsObject:key]
(BOOL) $6 = YES
(lldb) p (BOOL)[self.allKeys containsObject:key]
(BOOL) $7 = NO
```

Weirdly, hashes are the same, and `isEqual:` returns True. But for some reason, set contains returns `False`.

**Comment by dsanghan** [comment]
Its an NSInteger overflow on that key...

**Comment by dsanghan** [comment]
@krzyzanowskim  Maybe not use 31 as a prime on `PGPPartialKey`? Or use XOR.

**Comment by dsanghan** [comment]
On 32bit arch's the hashes are consistently higher than UINT32_MAX.

The issue is also occurring on 64-bit devices. Using `isEncrypted` in `[PGPPartialKey hash]` is somehow causing the NSSet mismatches to occur.

**Comment by krzyzanowskim** [comment]
hm... integer overflow is fine as long as it’s the same. Do tou have values I could use to reproduce, by any chance?

**Comment by dsanghan** [comment]
No. Its consistently happening, but the moment I modify the hash function a little bit, different keys start failing the test. Pretty weird.

**Comment by dsanghan** [comment]
Ok, so it turns out using `[NSSet setWithSet:<ObjectivePGP allKeys>]` uses the older hash stored in the set. If a subkey is added or a user changes or key decrypts, the hash isn't updated in the original set - so the contains fails. Using `[NSSet setWithArray:<ObjectivePGP allKeys>.allObjects]` fixes the issue by making it re-calculate the hashes on creating a new set.

**Comment by dsanghan** [comment]
This is what Apple has to say on the hash function:
```
If two objects are equal (as determined by the isEqual: method), they must have the same hash value. This last point is particularly important if you define hash in a subclass and intend to put instances of that subclass into a collection. If a mutable object is added to a collection that uses hash values to determine the object’s position in the collection, the value returned by the hash method of the object must not change while the object is in the collection. Therefore, either the hash method must not rely on any of the object’s internal state information or you must make sure the object’s internal state information does not change while the object is in the collection. Thus, for example, a mutable dictionary can be put in a hash table but you must not change it while it is in there. (Note that it can be difficult to know whether or not a given object is in a collection.)
```

**Comment by krzyzanowskim** [comment]
makes sense now. I'll address this issue later today

**Comment by krzyzanowskim** [comment]
@dsanghan the transition is not done fully yet, but can you test the current `develop` branch?

**Comment by krzyzanowskim** [comment]
ok, should be fixed now. please confirm.

**Comment by dsanghan** [comment]
Ok. Taking a look.

**Comment by dsanghan** [comment]
So went through all commits. Also tested on device, seems to be fine. I don't have too much experience with NSCopying so not super sure about 763f38c72dfb76a6e1274103c2df3b4cb9d9ffca , but looks good. We can close for now and I'll re-open if we see the issue again.

**Comment by dsanghan** [comment]
Actually, export/import is broken. 

```
NSSet *keys = [self.pgp importKeysFromFile:<keyring>];
PGPKey *key = keys.anyObject;
NSSet *keys = [self.pgp importKeysFromData:[key export:error]];
```
Assertion triggers on importing exported key.

**Comment by krzyzanowskim** [comment]
That's a separate issue, looks I broke something somewhere. investigating.

**Comment by krzyzanowskim** [comment]
I decided to revert the `NSSet` change as it causes more troubles than profits. The changes I just pushed address both, equality and export/import issues.

@dsanghan  I added a test to check the export/import, though if these part cause problems with a particular set of keys, please provide a test to reproduce.
