### ISSUE TITLE
[0.9.2] PGPMPI isEqual: / hash not implemented

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#82]
Its causing `isEqual:` to fail for public keys.

**Comment by krzyzanowskim** [comment]
so, this is after fix public key equality https://github.com/krzyzanowskim/ObjectivePGP/commit/4087b1aa847cf6c65c8893ed1a31698f25fe7aa3
makes sense. will fix and release 0.9.3

**Comment by krzyzanowskim** [comment]
Fixed on develop branch, please verify so I can prepare new release.

**Comment by dsanghan** [comment]
Nope. Still not fixed. Equality failures on PGPSignaturePacket.hashedSubpackets:

```

(lldb) po self.hashedSubpackets
<__NSArrayI 0x604000492e30>(
<PGPSignatureSubpacket: 0x60400122f680> type: 27 value: (
    1,
    2
),
<PGPSignatureSubpacket: 0x60400122fb00> type: 11 value: (
    9,
    8,
    7,
    3
),
<PGPSignatureSubpacket: 0x604001420aa0> type: 21 value: (
    10,
    9,
    8,
    11
),
<PGPSignatureSubpacket: 0x604001230ae0> type: 22 value: (
    2,
    3,
    1,
    0
),
<PGPSignatureSubpacket: 0x604001234960> type: 30 value: (
    1
),
<PGPSignatureSubpacket: 0x604001423980> type: 23 value: (
    128
),
<PGPSignatureSubpacket: 0x604001422460> type: 2 value: 2016-08-29 19:51:06 +0000,
<PGPSignatureSubpacket: 0x6040012342c0> type: 9 value: 98218111
)


(lldb) po packet.hashedSubpackets
<__NSArrayI 0x60400048fbe0>(
<PGPSignatureSubpacket: 0x604000a25a20> type: 27 value: (
    1,
    2
),
<PGPSignatureSubpacket: 0x6040012385e0> type: 11 value: (
    9,
    8,
    7,
    3
),
<PGPSignatureSubpacket: 0x604000a3bca0> type: 21 value: (
    10,
    9,
    8,
    11
),
<PGPSignatureSubpacket: 0x604001232dc0> type: 22 value: (
    2,
    3,
    1,
    0
),
<PGPSignatureSubpacket: 0x604000a3bf40> type: 30 value: (
    1
),
<PGPSignatureSubpacket: 0x604001232da0> type: 23 value: (
    128
),
<PGPSignatureSubpacket: 0x604000a311e0> type: 2 value: 2016-08-29 19:51:06 +0000,
<PGPSignatureSubpacket: 0x604000a22780> type: 9 value: 98218111
)
(lldb) p [self.hashedSubpackets isEqualToArray:packet.hashedSubpackets]
(BOOL) $28 = NO
```

**Comment by krzyzanowskim** [comment]
that need some tests, do you mind PR a test case for that?

**Comment by dsanghan** [comment]
@krzyzanowskim: Added a test in https://github.com/dsanghan/ObjectivePGP/commit/e18e4bfcd778a757ce81ed66d2ee4f8f6a29d1ea

**Comment by dsanghan** [comment]
The test is passing on develop, so seems to be a conflict with one of my commits.

**Comment by dsanghan** [comment]
Yup. Fix is working on develop. For some reason using `containsArmoredData:` instead of `isArmoredData:` is causing the test to fail on our branch but I can take a look at that. Closing.

**Comment by dsanghan** [comment]
Actually, its failing on the develop branch as well.

**Comment by dsanghan** [comment]
PR: https://github.com/krzyzanowskim/ObjectivePGP/pull/83

**Comment by dsanghan** [comment]
@krzyzanowskim: you'll want to change `XCTAssertEquals(..)` to `XCTAssertEqualObjects(keys1, keys2);` (test still fails though)

**Comment by krzyzanowskim** [comment]
Thanks. Found the issue. Should be good now.

**Comment by dsanghan** [comment]
Yup. Works now 👍
